package_name = "walletabi"
kotlin_multiplatform = true
kotlin_targets = ["jvm", "android", "native"]
kotlin_target_version = "2.2.20"
disable_java_cleaner = true
generate_serializable_types = true
cdylib_name = "walletabi"
